name: Hprofile Actions
on: workflow_dispatch

jobs: 
  Testing: 
    runs-on: ubuntu-latest
    steps: 
      - name: Code checkout
        uses: actions/checkout@v4  

      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
     
      - name: Maven test
        run: mvn test
     
      - name: Check style
        run: mvn checkstyle:checkstyle

      - name: Set up Sonar Scanner
        uses: Warchant/setup-sonar-scanner@v8
        with:
          version: '5.0.1.3006'
       
      - name: SonarQube Quality Gate Check
        uses: SonarSource/sonarqube-quality-gate-action@v1.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    
